# Generated by Django 3.0.8 on 2020-07-17 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_password_reset_time',
            fields=[
                ('user', models.CharField(max_length=155, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('task', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
